# @name Login
POST /v3/auth/login HTTP/1.1
Host: {{kinvoBaseUrl}}
Content-Type: application/json

{
    "email": "gutembergphilipe@gmail.com",
    "password": "laurinha"
}

###

GET /FinancialInstitution/GetAll HTTP/1.1
Host: kinvo2b-api.kinvo.com.br:443
Content-Type: application/json
Authorization: Bearer {{Login.response.body.data.accessToken}}