@portfolioId = 536142

# @name Login
POST /v3/auth/login HTTP/1.1
Host: {{kinvoBaseUrl}}
Content-Type: application/json

{
    "email": "gutembergphilipe@gmail.com",
    "password": "laurinha"
}

###

POST /portfolio-query/StatementConsolidation/GetPortfolioStatement
Host: {{kinvoBaseUrl}}
Content-Type: application/json
Authorization: Bearer {{Login.response.body.data.accessToken}}

{"portfolioId":"{{portfolioId}}","offset":0,"fetch":1000000}