services:
  postgres:
    image: postgres
    volumes:
      - ./Infra.Database.Postgres/Migrations/CreateDatabase.sql:/docker-entrypoint-initdb.d/CreateDatabase.sql
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"